### ISSUE TITLE
Add to AUR repo

### ISSUE THREAD

**Issue by Casul51** [matanui159/ReplaySorcery#1]
It'd help a lot with updates for arch users

**Comment by PowerMan2206** [comment]
I have 0 experience with this but brb Imma try

**Comment by matanui159** [comment]
@bennetthardwick is a big Arch fan and might know a thing or two :stuck_out_tongue_closed_eyes: 

Would be cool if it could integrate with the CI (which I currently only have for code checks) and the release tags. Either way if you're able to set one up feel free to add it to the readme.

**Comment by bennetthardwick** [comment]
> I have 0 experience with this but brb Imma try

@PowerMan2206 if you need a hand let me know and I can try and help

**Comment by PowerMan2206** [comment]
> if you need a hand let me know and I can try and help

@bennetthardwick thanks for the offer, but I have absolutely no idea what I'm doing. Looking at the PKGBUILDs of other packages, I think that this is way out of my range of understanding (at least for now). I tried and I failed, someone else will have to make an AUR package.

**Comment by leogx9r** [comment]
@matanui159 Here's the PKGBUILD for Arch. I didn't actually submit it to the AUR (yet) in case you want to own the package.

- `PKGBUILD`
```
_pkgname=ReplaySorcery
pkgname=replaysorcery-git
pkgver=r80.b70061f
pkgrel=1
pkgdesc="An open-source, instant-replay solution for Linux."
arch=('x86_64')
url="https://github.com/matanui159/ReplaySorcery"
license=('GPL')
depends=('nasm' 'libjpeg-turbo')
makedepends=('make' 'cmake' 'git')
source=("git+https://github.com/matanui159/ReplaySorcery.git"
        replay-sorcery.service
        replay-sorcery.conf)
sha256sums=('SKIP'
            '83248a950a0c8a4f56dd7d58be40cef7a864c17d04063a99ce7f056a36cad6f5'
            '1641e269de9fb6ff43666e0433c7ff55607d27764dc98d0f192e6889bcb0437b')
backup=(etc/xdg/replay-sorcery.conf)

pkgver() {
  cd "${srcdir}/${_pkgname}"

  # Get the version number.
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
  cd "${srcdir}/${_pkgname}"

  git submodule update --init
  cmake -B bin -DCMAKE_BUILD_TYPE=Release
  make -j$(nproc) -C bin
}

package() {
  cd "${srcdir}/${_pkgname}"

  install -Dm755 "bin/replay-sorcery" "${pkgdir}/usr/local/bin/replay-sorcery"
  install -Dm644 "${srcdir}/replay-sorcery.conf" "${pkgdir}/etc/xdg/replay-sorcery.conf"
  install -Dm644 "${srcdir}/replay-sorcery.service" "${pkgdir}/usr/lib/systemd/user/replay-sorcery.service"
}
```

- `.SRCINFO`
```
pkgbase = replaysorcery-git
	pkgdesc = An open-source, instant-replay solution for Linux.
	pkgver = r80.b70061f
	pkgrel = 1
	url = https://github.com/matanui159/ReplaySorcery
	arch = x86_64
	license = GPL
	makedepends = make
	makedepends = cmake
	makedepends = git
	depends = nasm
	depends = libjpeg-turbo
	backup = etc/xdg/replay-sorcery.conf
	source = git+https://github.com/matanui159/ReplaySorcery.git
	source = replay-sorcery.service
	source = replay-sorcery.conf
	sha256sums = SKIP
	sha256sums = 83248a950a0c8a4f56dd7d58be40cef7a864c17d04063a99ce7f056a36cad6f5
	sha256sums = 1641e269de9fb6ff43666e0433c7ff55607d27764dc98d0f192e6889bcb0437b

pkgname = replaysorcery-git

```

There's some fixed path madness I had to work around but that should work.

For local files I also included `replay-sorcery.service` and `replay-sorcery.conf`. These are the files below:

- `replay-sorcery.conf` -- Literally the defaults
```
offsetX = 0
offsetY = 0
width = 1920
height = 1080
framerate = 30
duration = 30
compressQuality = 70
outputFile = ~/Videos/ReplaySorcery_%F_%H-%M-%S.mp4
```

- `replay-sorcery.service` - Fixed path for Arch -- This path is broken when using the CMAKE variable hence it's manually fixed.
```
[Unit]
Description=ReplaySorcery: an open-source, instant-replay solution for Linux.

[Service]
Type=simple
ExecStart=/usr/local/bin/replay-sorcery
TimeoutStopSec=60
Restart=always

[Install]
WantedBy=graphical.target
```

**Comment by matanui159** [comment]
Thank you for this. @bennetthardwick is already working on this but these files will probably be useful.

**Comment by bennetthardwick** [comment]
@leogx9r I wrote this PKGBUILD, do you have any feedback?

```
pkgname=replay-sorcery
pkgver=0.2.2
pkgrel=1
pkgdesc="An open-source, instant-replay solution for Linux"
arch=("i686" "x86_64")
license=("GPL-3.0")
makedepends=("cmake" "make" "git" "pkg-config" "nasm")
url="https://github.com/matanui159/ReplaySorcery"
source=("${pkgname}::git+${url}.git#tag=${pkgver}")
sha256sums=("SKIP")

prepare() {
  mkdir -p "${pkgname}/build"
  git -C "${pkgname}" checkout 
  git -C "${pkgname}" submodule update --init --recursive --depth=1
}

build() {
  cd "${pkgname}" || exit 1
  cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DRS_SYSTEMD_DIR=/usr/lib/systemd/user
  make -C build
}

package() {
  cd "${pkgname}" || exit 1
  make -C build DESTDIR=${pkgdir} install
}
```

**Comment by leogx9r** [comment]
@bennetthardwick You're missing the depends line:

```
depends=('nasm' 'libjpeg-turbo')
```

In addition, since you're not building a `-git` package, you should use the source directly as a URI (https://github.com/matanui159/ReplaySorcery/archive/0.2.2.tar.gz) and **not** skip the checksum since that's generally used only for `-git` releases.

Aside from that, my personal recommendation is to include a default configuration file at the XDG path (that's backed up) so it's tracked by the package -- avoiding stray files when you uninstall. You could also add `-j$(nproc)` to speed up building for multi-core users.

Seems the fixed path issue was resolved since I made the above so I don't see anything wrong with yours.

**Comment by matanui159** [comment]
`nasm` is a build dependency and `libjpeg-turbo` isn't required since it's built as part of the project and statically linked in.

I think also @bennetthardwick told me that the source downloads from GitHub don't include submodules.

**Comment by leogx9r** [comment]
Ah I missed that somehow, ignore the dependency part. If submodules are broken from source downloads, I guess that's an adequate work-around.

**Comment by jkhsjdhjs** [comment]
> You could also add -j$(nproc) to speed up building for multi-core users.

Multi-core users can set the `-j` flag in `/etc/makepkg.conf` by changing the variable `MAKEFLAGS`. Setting `-j$(nproc)` would override the users personal preference, that's why I recommend against adding this to the PKGBUILD.

**Comment by benjamimgois** [comment]
@PowerMan2206 I would like to create a GUI to config ReplaySorcery inside [GOverlay](https://github.com/benjamimgois/goverlay). The AUR package would help a lot, since i can make Replaysorcery as a dependent package.

**Comment by murlakatamenka** [comment]
https://aur.archlinux.org/packages/replay-sorcery-git

**Comment by matanui159** [comment]
It has been added to the readme.

@bennetthardwick is looking into also having a non-`-git` version that is hooked up to the CI

**Comment by matanui159** [comment]
There is now a versioned AUR package at [replay-sorcery](https://aur.archlinux.org/packages/replay-sorcery). This will be updated with each tagged release.

**Comment by matanui159** [comment]
Also @murlakatamenka there is now a proper default config file that gets installed by the cmake file: [replay-sorcery.default.conf](https://github.com/matanui159/ReplaySorcery/blob/master/replay-sorcery.default.conf)
