### ISSUE TITLE
X11 warning: BadMatch (invalid parameter attributes)

### ISSUE THREAD

**Issue by bwyan86** [matanui159/ReplaySorcery#10]
Hello again.

I noticed a potentially new bug which seems to be slowly and persistently eating my memory.

If I run `journalctl --user -fu replay-sorcery`, i get this line repeated many times per second:
`replay-sorcery[3496]: X11 warning: BadMatch (invalid parameter attributes)`

BTW: I'm not entirely sure what version of ReplaySorcery I'm on, as I can't seem to find a version number in the output of the program.

Specs:
Ubuntu 20.04
Mesa 20.1.4
i3wm (no compositor)

**Comment by matanui159** [comment]
Does the warning keep happening? That sometimes happens when the computer is asleep of suspended. Alternatively it could also happen if the grab rectangle is incorrect (by default its a 1080p region).

As for the memory usage, does it keep growing forever? It should grow for the first 30 seconds or so until the buffer fills up but after that it should start overwriting itself again (it may still grow a bit more or shrink later depending on the complexity of what is on the screen at the time).

**Comment by bwyan86** [comment]
@matanui159 Thanks for the info. I found the issue regarding the error in the logs thanks to your explanation. It turns out that the geometry of the video recording that I configured does **not** match the startup condition of my xrandr layout.

I have configured the geometry to be a 1440p recording of my primary monitor with a secondary 1080p monitor on the left, but when I start my DE, the secondary monitor is disabled by default (on purpose). As soon as I then enable the secondary monitor, the error messages stop, so you are indeed correct.

As for the memory consumption, it does seem to persistently creep up and, so far, I have seen it as high as ~30% of 16 GB total with the following settings:
```
offsetX = 1920
width = 2560
height = 1440
framerate = 30
duration = 180
compressQuality = 70
outputFile = ~/Videos/ReplaySorcery/%F_%H-%M-%S.mp4
```

Otherwise, feel free to close this issue, then I can perhaps get back to you in a separate issue, if the memory situation gets out of hand.

**Comment by matanui159** [comment]
If you want lower memory usage, I find for higher resolutions lowering the JPEG quality is fine. I've been using 50 for my setup with no problems (I should probably update the readme).

**Comment by bwyan86** [comment]
@matanui159 I have attempted to make a (my first ever) [pull request](https://github.com/matanui159/ReplaySorcery/pull/11) following [this guide](https://linuxhint.com/pull_request_github/). I have merely made an addition to the README, which should hopefully be helpful to others in regards to this issue. Otherwise, feel free to reject it or reformulate my sentence.
