### ISSUE TITLE
Is there a windows alternative? 

### ISSUE THREAD

**Issue by 3top1a** [matanui159/ReplaySorcery#107]
I started playing with my friends on Windows the other week because of multiplayer, and I want something to capture the entire screen (so not Nvidia experience) but still be performant enough to not cause lag.

Is there any app like that?

**Comment by matanui159** [comment]
Iirc, AMD ReLive let you capture the entire screen so I'm surprised nVidia experience won't. I have considered porting this to Windows or Mac OSX (notably for Intel devices, and also an open source and cross platform alternative to proprietary software). Alternatively OBS has a replay buffer feature that you might be interested in.

**Comment by Invades** [comment]
> and I want something to capture the entire screen (so not Nvidia experience)

It can literally do that though? Please do some research yourself before making an issue [**since it's literally just a checkbox in the privacy settings on the overlay**](https://www.hackint0sh.org/how-to-record-desktop-with-shadowplay/) (1 google search away).

**Comment by 3top1a** [comment]
Oh crap sorry, I assumed shadow play was only for games since it only worked for NVIDIA game works enabled games
