### ISSUE TITLE
81% crashing to compile (Ubuntu 20.04 based distro)

### ISSUE THREAD

**Issue by shigutso** [matanui159/ReplaySorcery#115]
**Describe the bug**
https://pastebin.com/az8Pspct

**Desktop:**
 - Distro: KDE Neon
 - Desktop Environment: KDE
 - Window Manager: KDE
 - CPU: AMD Ryzen 3 3100
 - GPU: AMD Radeon 5500 XT

**Configuration:**
N/A

**Logs:**
https://pastebin.com/az8Pspct

**Comment by matanui159** [comment]
Looks like that code isn't properly written to handle XCB not existing. As a workaround install libxcb development libraries (`libxcb` on Ubuntu I believe?) which you probably want to do anyway since X11 screen grabbing and key-press detection won't work without it.

**Comment by shigutso** [comment]
Thanks for the help
I have many XCB packages installed:
https://pastebin.com/DbQgP1wJ

Could it be the version is fairly old due to Ubuntu 20.04 repositories?

These are the XCB packages available to install:
https://pastebin.com/XPdQKqSk

**Comment by matanui159** [comment]
Can you delete your bin folder and share your output for `cmake -B bin`?

**Comment by shigutso** [comment]
Sorry for late reply
For other reasons I moved from KDE Neon to Manjaro this weekend and installed replay-sorcey from the AUR, it's now working properly.

I assume it was due to some messy libs I installed in the past.
I will close this
Thanks for your help!
