### ISSUE TITLE
Option to change the activation Key

### ISSUE THREAD

**Issue by benjamimgois** [matanui159/ReplaySorcery#12]
@matanui159 Firstl thanks for this application. The latest git is working very well for me now.... i think Linux really need something like this. Is it possible to change the key combination to a custom one ? Maybe use a simple F9 or F8.

**Comment by matanui159** [comment]
This is in the Todo, biggest problem is translating strings (something like "Super+Ctrl+R") to modifiers and keys. Not sure if theres something like this in xlib already

**Comment by matanui159** [comment]
Added in faab136338f39ec5ca2447115e75ccbfeb07e9f5.
