### ISSUE TITLE
Unable To Build In Kubuntu 21.04

### ISSUE THREAD

**Issue by intelligentgaming** [matanui159/ReplaySorcery#120]
Hi there, I'm really struggling to get this piece of software installed on Kubuntu 21.04.

From your instructions, it is not really clear what libraries you need to install for Ubuntu based distributions, but I seem to have them installed now.

For reference, they are.

git
cmake
ffmpeg
libx11-xcb-dev
libavutil-dev
libavformat-dev
libavdevice-dev
libavcodec-dev
libavfilter-dev
libdrm-dev
libpulse-dev

I saw a previous issue post that suggested installing the below. 

sudo apt-get install libavutil-dev libavformat-dev libavdevice-dev libavcodec-dev libavfilter-dev

But now I cannot follow the rest of the instructions without getting errors. 

git submodule update --init

fatal: not a git repository (or any of the parent directories): .git

cmake -B bin -DCMAKE_BUILD_TYPE=Release

CMake Error at /usr/share/cmake-3.18/Modules/ExternalProject.cmake:2555 (message):
  No download info given for 'backtrace' and its source directory:

   /home/ryan/Downloads/ReplaySorcery-0.6.0/dep/libbacktrace

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/ExternalProject.cmake:3206 (_ep_add_download_command)
  CMakeLists.txt:101 (ExternalProject_Add)

Does this software even work on non Arch systems or am I wasting my time?

I'm happy to do some troubleshooting but I feel like I am hitting a brick wall here.

**Comment by subiesubiesubie** [comment]
do

git clone https://github.com/matanui159/ReplaySorcery.git

then try the rest of the instructions, worked for me on KDE Neon 20.04

**Comment by intelligentgaming** [comment]
> do
> 
> git clone https://github.com/matanui159/ReplaySorcery.git
> 
> then try the rest of the instructions, worked for me on KDE Neon 20.04

Thank you, that worked, now just need GOverlay to recognise that ReplaySorcery is installed.
