### ISSUE TITLE
DEs do not use the graphical-session target

### ISSUE THREAD

**Issue by melvyn2** [matanui159/ReplaySorcery#121]
**Describe the bug**
Some desktop environments do not start the graphical-session target, so the replay-sorcery target won't start even when enabled.
According to https://unix.stackexchange.com/a/598055 , default.target will be started by these DEs, and I have confirmed that using this target instead does lead to a working startup (with kmsgrab- X11grab may need to be started later).
It seems that [GNOME will start this target](https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/13), but I'm not aware of any other DEs doing so.

**Desktop:**
 - Distro: Arch Linux
 - Desktop Environment: KDE
 - Window Manager: KWin Wayland
 - CPU: Intel Core i9-9900k
 - GPU: AMD Radeon RX 580

**Configuration:**
[replay-sorcery.conf](https://github.com/matanui159/ReplaySorcery/files/6872909/replay-sorcery.conf.txt)

**Comment by matanui159** [comment]
Sadly `default.target` will make X11 fail sometimes. What does KDE use for it's graphical target? Maybe I can have it support both?

**Comment by melvyn2** [comment]
Looking a bit further, it seems KDE _should_ be using `graphical-session.target`. Maybe KDE isn't using systemd by default and it needs to be enabled.
I can't verify now but I'll look further into this when I am able again.

**Comment by melvyn2** [comment]
Looking a bit further, it seems KDE _should_ be using `graphical-session.target`. Maybe KDE isn't using systemd by default and it needs to be enabled.
I can't verify now but I'll look further into this when I am able again.

**Comment by melvyn2** [comment]
systemd startup for KDE needs to be enabled with `kwriteconfig5 --file startkderc --group General --key systemdBoot true`. Once it is, the `graphical-session.target` will be started properly. I would recommend adding `PartOf=graphical-session.target` to the `[Unit]` section of `replay-sorcery.service` however this isn't completely required because it should be stopped when the session ends anyways.
