### ISSUE TITLE
Record one monitor / repositioning of recoring area

### ISSUE THREAD

**Issue by Alfenstein8** [matanui159/ReplaySorcery#126]
**Is your feature request related to a problem? Please describe.**
I can't record only one screen. I have three monitors of different resolutions and positions. I only want to record the game on the monitor in the middle.
![Screenshot from 2021-08-16 23-30-47](https://user-images.githubusercontent.com/47451379/129633395-d8446973-2f80-4958-81f0-601aa1d24542.png)

**Describe the solution you'd like**
The optimal solution would be to be able to choose what screen should be recorded.

**Describe alternatives you've considered**
The other way is to reposition the recording area to a different spot, by manually typing the coordinate of the top left corner of the monitor that should be recorded, and applying the monitors' resolution.

**Comment by matanui159** [comment]
Use `videoX`/`videoY`/`videoWidth`/`videoHeight` in the config file. Please read the documentation:
https://github.com/matanui159/ReplaySorcery#configuration
https://github.com/matanui159/ReplaySorcery/blob/master/sys/replay-sorcery.conf#L26
