### ISSUE TITLE
Installation failed on Linux Mint 20

### ISSUE THREAD

**Issue by ocmann** [matanui159/ReplaySorcery#130]
Error in installation when follow example as in video
https://www.youtube.com/watch?v=bM9xiXKZwtc

 XXXn@pcman:~/ReplaySorcery$ sudo make -C bin install
make: Entering directory '/home/ocman/ReplaySorcery/bin'
make[1]: Entering directory '/home/ocman/ReplaySorcery/bin'
make[2]: Entering directory '/home/ocman/ReplaySorcery/bin'
make[2]: Leaving directory '/home/ocman/ReplaySorcery/bin'
[ 18%] Built target backtrace
make[2]: Entering directory '/home/ocman/ReplaySorcery/bin'
make[2]: Leaving directory '/home/ocman/ReplaySorcery/bin'
make[2]: Entering directory '/home/ocman/ReplaySorcery/bin'
[ 20%] Building C object CMakeFiles/replay-sorcery.dir/src/device/x11dev.c.o
In file included from /home/ocman/ReplaySorcery/src/device/x11dev.c:20:
/home/ocman/ReplaySorcery/src/device/x11dev.h:43:44: error: unknown type name ‘uint32_t’
   43 | int rsXClientGetKeyCode(RSXClient *client, uint32_t sym);
      |                                            ^~~~~~~~
/home/ocman/ReplaySorcery/src/device/x11dev.c: In function ‘xclientError’:
/home/ocman/ReplaySorcery/src/device/x11dev.c:27:9: error: ‘XCB_CONN_ERROR’ undeclared (first use in this function)
   27 |    case XCB_CONN_ERROR:
      |         ^~~~~~~~~~~~~~
/home/ocman/ReplaySorcery/src/device/x11dev.c:27:9: note: each undeclared identifier is reported only once for each function it appears in
/home/ocman/ReplaySorcery/src/device/x11dev.c:29:9: error: ‘XCB_CONN_CLOSED_EXT_NOTSUPPORTED’ undeclared (first use in this function)
   29 |    case XCB_CONN_CLOSED_EXT_NOTSUPPORTED:
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ocman/ReplaySorcery/src/device/x11dev.c:31:9: error: ‘XCB_CONN_CLOSED_MEM_INSUFFICIENT’ undeclared (first use in this function)
   31 |    case XCB_CONN_CLOSED_MEM_INSUFFICIENT:
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ocman/ReplaySorcery/src/device/x11dev.c:33:9: error: ‘XCB_CONN_CLOSED_REQ_LEN_EXCEED’ undeclared (first use in this function)
   33 |    case XCB_CONN_CLOSED_REQ_LEN_EXCEED:
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ocman/ReplaySorcery/src/device/x11dev.c:35:9: error: ‘XCB_CONN_CLOSED_PARSE_ERR’ undeclared (first use in this function)
   35 |    case XCB_CONN_CLOSED_PARSE_ERR:
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/ocman/ReplaySorcery/src/device/x11dev.c:37:9: error: ‘XCB_CONN_CLOSED_INVALID_SCREEN’ undeclared (first use in this function)
   37 |    case XCB_CONN_CLOSED_INVALID_SCREEN:
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ocman/ReplaySorcery/src/device/x11dev.c: At top level:
/home/ocman/ReplaySorcery/src/device/x11dev.c:101:5: warning: no previous prototype for ‘rsXClientGetKeyCode’ [-Wmissing-prototypes]
  101 | int rsXClientGetKeyCode(RSXClient *client, uint32_t sym) {
      |     ^~~~~~~~~~~~~~~~~~~
/home/ocman/ReplaySorcery/src/device/x11dev.c:25:12: warning: ‘xclientError’ defined but not used [-Wunused-function]
   25 | static int xclientError(int error) {
      |            ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/replay-sorcery.dir/build.make:401: CMakeFiles/replay-sorcery.dir/src/device/x11dev.c.o] Error 1
make[2]: Leaving directory '/home/ocman/ReplaySorcery/bin'
make[1]: *** [CMakeFiles/Makefile2:133: CMakeFiles/replay-sorcery.dir/all] Error 2
make[1]: Leaving directory '/home/ocman/ReplaySorcery/bin'
make: *** [Makefile:130: all] Error 2
make: Leaving directory '/home/ocman/ReplaySorcery/bin'4: error: unknown type name ‘uint32_t’

**Logs:**
Please run `journalctl --user -eu replay-sorcery -n 100 > replay-sorcery.log` and upload the result.

**Comment by matanui159** [comment]
There is currently an issue where it doesn't compile properly if you don't have the libxcb development libraries so please install that first (you will probably want them anyway if you're using X11).

**Comment by caecilliusinhorto** [comment]
I have this same issue but compilation still fails even with xcb dev libraries installed.
