### ISSUE TITLE
Docs: mention how it stores it before rendering

### ISSUE THREAD

**Issue by LiamDawe** [matanui159/ReplaySorcery#14]
Unless I overlooked it, one big glaring omission from the current readme is where and how the JPEG captures are stored before it renders them into a video file.

Is it kept in memory? Constantly saving them to a temp file/folder or what? This would be a nice point to clear up. It would prevent some confusion on how it operates in the background :)

**Comment by matanui159** [comment]
It stores it in a rotating buffer. I might add it to the readme along with a general code structure overview

**Comment by matanui159** [comment]
This has now been added to the readme.
