### ISSUE TITLE
High profile is not supported

### ISSUE THREAD

**Issue by ghost** [matanui159/ReplaySorcery#140]
**Describe the bug**
AAC High profile is not supported. Iirc I did have this working before 21.10 but now it seems to not be. Other profiles work fine. aac-enc, gstreamer, libav, ect. all have been installed but it just doesn't seem to want to work. Again, low and main work fine.

**Desktop:**
 - Distro: Kubuntu 21.10
 - Desktop Environment: Plasma
 - Window Manager: Kwin
 - CPU: Ryzen 3 2200g
 - GPU: Vega 8 iGPU

[replay-sorcery.log](https://github.com/matanui159/ReplaySorcery/files/7532577/replay-sorcery.log)

videoWidth = auto
videoHeight = auto
scaleWidth = auto
scaleHeight = auto
videoInput = hwaccel
videoDevice = auto
videoFramerate = 60
recordSeconds = 30
videoEncoder = vaapi_hevc
videoProfile = high
videoPreset = slow
videoQuality = auto
videoBitrate = auto
videoGOP = 30
audioEncoder = aac
audioProfile = high
audioDevice = alsa_output.usb-FiiO_K3-00.analog-stereo.monitor
keyMods = ctrl+super
keyName = r
outputCommand = notify-send -i /usr/share/icons/hicolor/128x128/apps/goverlay.png Video_Saved_in_the_home_folder
outputFile = /home/yup/Videos/%F_%H-%M-%S.mp4

I'm assuming it's just some sort of missing dependency. If so, adding that as a suggestion for Ubuntu users would be helpful.

Edit: With just aac instead of fdk, I get this:

Saving video to '/home/yup/Videos/2021-11-13_11-46-38.mp4'...
Encoder not found: libfdk_aac
 - /home/yup/ReplaySorcery/src/encoder/ffenc.c:155 (rsFFmpegEncoderCreate)
 - /home/yup/ReplaySorcery/src/audio/fdkenc.c:25 (rsFdkEncoderCreate)
 - /home/yup/ReplaySorcery/src/audio/aencoder.c:34 (rsAudioEncoderCreate)
 - /home/yup/ReplaySorcery/src/audio/abuffer.c:38 (audioBufferGetEncoder)
 - /home/yup/ReplaySorcery/src/audio/abuffer.c:35 (audioBufferGetEncoder)
 - /home/yup/ReplaySorcery/src/audio/abuffer.c:120 (rsAudioBufferGetParams)
 - /home/yup/ReplaySorcery/src/main.c:103 (mainOutput)
 - /home/yup/ReplaySorcery/src/main.c:215 (main)
 - ../sysdeps/nptl/libc_start_call_main.h:58 (__libc_start_call_main)
 - ../csu/libc-start.c:409 (__libc_start_main_impl)
Failed to create FDK-AAC audio encoder: Encoder not found
High profile is not supported

I have libfdk-aac2 installed though...

**Comment by matanui159** [comment]
For `libfdk-aac` support you need FFmpeg to be built with it enabled. Run `ffmpeg -encoders | grep aac` to check your supported AAC encoders. Iirc I don't think high profile is supported by FFmpeg's native AAC encoder.

**Comment by ghost** [comment]
Yeah I was suspecting that. I swear I had this working before though, and I did not compile ffmpeg myself.


ffmpeg version 4.4-6ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-7ubuntu1)
  configuration: --prefix=/usr --extra-version=6ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avformat    configuration: --prefix=/usr --extra-version=6ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
 A..... aac                  AAC (Advanced Audio Coding)

**Comment by matanui159** [comment]
Yeah libfdk is not in that list. Iirc most distributions don't have libfdk compiled into their build of FFmpeg. The builtin AAC encoder tends to be good enough, even without high profile support.
