### ISSUE TITLE
nvidia-frame buffer capture?

### ISSUE THREAD

**Issue by IcyAlmond** [matanui159/ReplaySorcery#141]
I'm not very knowledgeable on this topic but I use https://github.com/keylase/nvidia-patch to enable nvidia-fbc on consumer hardware (the same thing which shadowplay uses) in combination with https://gitlab.com/fzwoch/obs-nvfbc to record with nvidia frame buffer capture on OBS.

I think it uses much less resource when compared to NVENC, but it can only record the whole screen (AFAIK)

Has this been considered?

**Comment by matanui159** [comment]
Perhaps. See discussion at #9
