### ISSUE TITLE
Encoder not found

### ISSUE THREAD

**Issue by niansa** [matanui159/ReplaySorcery#144]
**Describe the bug**

**Desktop:**
 - Distro: opensuse tumbleweed
 - Desktop Environment: Plasma
 - Window Manager: kwin
 - CPU: Intel i3 8th gen
 - GPU: AMD RX 580

**Configuration:**
Default config

**Logs:**

    Reading config file '/usr/local/etc/replay-sorcery.conf'...
    Setting 'logLevel' to 'info'...
    Setting 'traceLevel' to 'error'...
    Setting 'recordSeconds' to '30'...
    Setting 'videoInput' to 'auto'...
    Setting 'videoDevice' to 'auto'...
    Setting 'videoX' to '0'...
    Setting 'videoY' to '0'...
    Setting 'videoWidth' to 'auto'...
    Setting 'videoHeight' to 'auto'...
    Setting 'videoFramerate' to '30'...
    Setting 'videoEncoder' to 'auto'...
    Setting 'videoProfile' to 'baseline'...
    Setting 'videoPreset' to 'fast'...
    Setting 'videoQuality' to '28'...
    Setting 'videoBitrate' to 'auto'...
    Setting 'videoGOP' to '30'...
    Setting 'scaleWidth' to 'auto'...
    Setting 'scaleHeight' to 'auto'...
    Setting 'audioInput' to 'auto'...
    Setting 'audioDevice' to 'auto'...
    Setting 'audioSamplerate' to '44100'...
    Setting 'audioEncoder' to 'auto'...
    Setting 'audioProfile' to 'low'...
    Setting 'audioBitrate' to 'auto'...
    Setting 'controller' to 'auto'...
    Setting 'keyName' to 'r'...
    Setting 'keyMods' to 'ctrl+super'...
    Setting 'outputFile' to '~/Videos/ReplaySorcery/%F_%H-%M-%S.mp4'...
    Setting 'outputCommand' to 'notify-send ReplaySorcery "Saved replay as %s"'...
    Failed to open config file '/home/nils/.config/replay-sorcery.conf': No such file or directory
    ReplaySorcery  Copyright (C) 2020-2021  ReplaySorcery developers
    This program comes with ABSOLUTELY NO WARRANTY.
    This is free software, and you are welcome to redistribute it
    under certain conditions; see COPYING for details.
    FFmpeg version: 4.4.1
    Created X11 device
    Encoder not found: libx264
     - /home/nils/Programme/OSS/ReplaySorcery/src/encoder/ffenc.c:155 (rsFFmpegEncoderCreate)
     - /home/nils/Programme/OSS/ReplaySorcery/src/encoder/x264enc.c:30 (rsX264EncoderCreate)
     - /home/nils/Programme/OSS/ReplaySorcery/src/encoder/encoder.c:92 (rsVideoEncoderCreate)
     - /home/nils/Programme/OSS/ReplaySorcery/src/main.c:182 (main)
     - ../sysdeps/x86_64/start.S:116 ((null))
    Failed to create x264 encoder: Encoder not found
    Encoder not found: libopenh264
     - /home/nils/Programme/OSS/ReplaySorcery/src/encoder/ffenc.c:155 (rsFFmpegEncoderCreate)
     - /home/nils/Programme/OSS/ReplaySorcery/src/encoder/openh264enc.c:30 (rsOpenH264EncoderCreate)
     - /home/nils/Programme/OSS/ReplaySorcery/src/encoder/encoder.c:98 (rsVideoEncoderCreate)
     - /home/nils/Programme/OSS/ReplaySorcery/src/main.c:182 (main)
     - ../sysdeps/x86_64/start.S:116 ((null))
    Failed to create OpenH264 encoder: Encoder not found
    Function not implemented
     - /home/nils/Programme/OSS/ReplaySorcery/src/main.c:238 (main)
     - ../sysdeps/x86_64/start.S:116 ((null))

**Comment by matanui159** [comment]
Make sure your FFmpeg has H.264 support. Check `ffmpeg -encoders | grep h264`

**Comment by niansa** [comment]
That was it.
