### ISSUE TITLE
amdgpu crashes with hardware accel

### ISSUE THREAD

**Issue by bgkillas** [matanui159/ReplaySorcery#145]
**Describe the bug**
if i have vivaldi/discord have hardware acceleration enabled using the flags
`--use-gl=desktop --enable-features=VaapiVideoDecoder
`
and im watching a video rarely and seemingly at random my gpu crashes and i get lots of random colors on my screen
it did seem to happen more so with kms_service than hwaccel
**Desktop:**
 - Distro: [arch/testing]
 - Desktop Environment: [kde/x11]
 - Window Manager: [kwin]
 - CPU: [AMD Ryzen 3600X]
 - GPU: [AMD Radeon 5500 XT]

**Configuration:**
[replay.txt](https://github.com/matanui159/ReplaySorcery/files/7774959/replay.txt)

**Logs:**
replay output:
[replaylog.txt](https://github.com/matanui159/ReplaySorcery/files/7774963/replaylog.txt)
replay kms output:
[replaykmslog.txt](https://github.com/matanui159/ReplaySorcery/files/7774964/replaykmslog.txt)
dmesg of the crash output:
[dmesg.txt](https://github.com/matanui159/ReplaySorcery/files/7774966/dmesg.txt)

**Comment by bgkillas** [comment]
oh and i think this is related to replay sorcery because during shutdown it gets stuck at replay sorcery kms service

**Comment by bgkillas** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5359 oh its a mesa thing oops

**Comment by jannuary** [comment]
It would seem I have a similar issue - the GPU consistantly glitches out when leaving suspend if the kms service is on.
