### ISSUE TITLE
Failed to create X11 Device: Function not Implemented (Arch)

### ISSUE THREAD

**Issue by LoreRealm** [matanui159/ReplaySorcery#156]
**Describe the bug**
![Screenshot_20220413_211953](https://user-images.githubusercontent.com/22435766/163313002-8891bbfe-52ac-4ee4-8e3d-a509993f8a97.png)

Unable to connect to pipe in x11 doesn't work automatically and doesn't work when called either showing broken pipe x11 server could not detect x11 display size and function not implemented 

**Desktop:**
 - Distro: [Arch linux]
 - Desktop Environment: [KDE]
 - Window Manager: [KWIN]
 - CPU: [AMD RYZEN 2700x]
 - GPU: [AMD RADEON 6800xt]

**Configuration:**
[.config replay-sorcery.txt](https://github.com/matanui159/ReplaySorcery/files/8486195/replay-sorcery.txt)
[replay-sorcery-usr-etc.txt](https://github.com/matanui159/ReplaySorcery/files/8486200/replay-sorcery-usr-etc.txt)

Please upload your copy of `/usr/local/etc/replay-sorcery.conf` (`/usr/etc/replay-sorcery.conf` on Arch) and a copy of `~/.config/replay-sorcery.conf` if it exists.

**Logs:**
[replay-sorcery.log](https://github.com/matanui159/ReplaySorcery/files/8486205/replay-sorcery.log)

Please run `journalctl --user -eu replay-sorcery -n 100 > replay-sorcery.log` and upload the result.

**Comment by matanui159** [comment]
My first guess is it is failing because you're setting `videoDevice` to `card0:50` which is a KMS device name. For X11 you should use an X11 display name or just leave it as auto and it should be able to correctly detect a default name

**Comment by LoreRealm** [comment]
I got replay-sorcery working with goverlay instead closing issue
