### ISSUE TITLE
Cannot save replay video with terminal command, only X11 keyboard shortcut.

### ISSUE THREAD

**Issue by kode54** [matanui159/ReplaySorcery#162]
**Describe the bug**
As I am using Gnome Wayland on Arch, I am attempting to use the hwaccel mode with the kms service, and have Gnome configured with a custom keyboard shortcut to run `/usr/bin/replay-sorcery save`. Attempting to run this from a terminal shows that it's failing as well.

**Desktop:**
 - Distro: Arch Linux
 - Desktop Environment: GNOME Wayland
 - Window Manager: Mutter
 - CPU: AMD Ryzen 7 2700
 - GPU: AMD RX 480 8GB

**Configuration:**
[etc-replay-sorcery.conf.txt](https://github.com/matanui159/ReplaySorcery/files/9582485/etc-replay-sorcery.conf.txt)
[home-replay-sorcery.conf.txt](https://github.com/matanui159/ReplaySorcery/files/9582486/home-replay-sorcery.conf.txt)

**Logs:**
[replay-sorcery.log](https://github.com/matanui159/ReplaySorcery/files/9582476/replay-sorcery.log)

**Notes:**
Attempting to run `/usr/bin/replay-sorcery save` emits:
```
Real user ID: 1000
Effective user ID: 1000
Failed to connect socket: No such file or directory
No such file or directory
```

The keyboard shortcut works under X11, but the save terminal command doesn't work there, either.

**Comment by matanui159** [comment]
You have to set `controller = command` in the config

**Comment by kode54** [comment]
Oh, sorry, didn't realize that.
