### ISSUE TITLE
Keycombos for different amount of durations

### ISSUE THREAD

**Issue by 0neGuyDev** [matanui159/ReplaySorcery#22]
At certain times I feel that I only need to capture the last 15 seconds, but sometimes you need 30 or even 60 seconds... A way of binding keycombos for each duration would be nice. 

This might need major reworks if the duration is locked when replay-sorcery starts... But I haven't really checked the code...

**Comment by pseregiet** [comment]
Saving shorter video than what you specified in the config (as that decides how big the buffer is for audio and video frames) is easy. Just a question of how to handle the extra keybindings. Adding one or 2 additional key combos for a shorter clip save would be easy, but perhaps a system where you can specify arbitrary number of key combos would be preferable.

**Comment by pseregiet** [comment]
In the meantime you can just use ffmpeg to cut the video. It doesn't reencode, just copies the correct amount of frames to a new file, so it should take only a second or two

ffmpeg -ss 00:30:00 -i input.mp4 -to 00:30:00 -c copy output.mp4

To cut the last 30 seconds from input.mp4 and paste it to output.mp4 (-ss is the start position, -to is the length)

**Comment by 0neGuyDev** [comment]
> In the meantime you can just use ffmpeg to cut the video. It doesn't reencode, just copies the correct amount of frames to a new file, so it should take only a second or two

Funny you should say that as I have been using `ffmpeg` to cut the video :p 

> Just a question of how to handle the extra keybindings

As a start you could probably just have 2-3 bindings, but ideally you could be able to pass `keyCombos` and then depending on the number you'd have a range from `keyCombo1` to `keyCombo10` or whatever you set it to instead of the current `keyCombo` and then to be able to support older configs you could just make `keyCombo` = `keyCombo1`

**Comment by pseregiet** [comment]
Right right. Well it's not like I have a say here, just thought I'd comment on it. We'll see what matanui says

**Comment by matanui159** [comment]
I'm not sure there would be much use to this cause it's usually hard to tell how much time you need. A better imo solution would be some UI that opens up when you save the video that allows you to trim it. 

This is currently technically possible using `postOutputCommand`. Just choose you favourite editor and give the output file a consistent name and then set the command to `<editor> <video file>` (might be different for certain editors).

Support for unique file names (via timestamps) in output commands (via some special syntax) is something I want to implement at some point as well.

**Comment by pseregiet** [comment]
Yes you can even use dmenu/rofi for a nice prompt to enter the duration/filename etc. Then the program would have to use the ouput of system call though.

**Comment by 0neGuyDev** [comment]
> This is currently technically possible using `postOutputCommand`. Just choose you favourite editor and give the output file a consistent name and then set the command to `<editor> <video file>` (might be different for certain editors).

Honestly never considered using `postOutputCommand` for that...

> You can even use dmenu/rofi for a nice prompt

I might have to do this then :p

**Comment by Calinou** [comment]
For those looking for a graphical utility to cut videos losslessly, you can use [Lossless Cut](https://github.com/mifi/lossless-cut).

**Comment by matanui159** [comment]
Just doing some spring cleaning and I think the `postOutputCommand` is probably best here, I'll open another issue for allowing formatting of the command options.
