### ISSUE TITLE
Set compression quality automatically depending on available system memory

### ISSUE THREAD

**Issue by Calinou** [matanui159/ReplaySorcery#26]
I use a PC with 32 GB of RAM, most of it being unused in general. I noticed ReplaySorcery doesn't take that much RAM with the default buffer length and compression quality (30 seconds, quality 70). Even with the buffer length set to 5 minutes and the quality set to 90, it's using only about 10% of my system RAM (with a game running).

Would it be possible to add an `auto` setting which sets the compression quality automatically depending on the buffer length and available system memory? It would probably constrain the value to reasonable bounds (like 65..95).

That said, we may not want to go overboard. With a 2560×1440 display and the quality set to 100, here's what the memory usage graph looks like after playing for 5 minutes and exporting the video:

![image](https://user-images.githubusercontent.com/180032/92257466-90065400-eed5-11ea-9156-501d51fc580f.png)

(There might be a memory leak here, not sure.)

Either way, this could improve the out-of-the-box user experience on high-end setups.

**Comment by matanui159** [comment]
Might close this issue since the newer versions have much lower memory usage, and can also scale-down if you want even lower memory usage or faster encoding speed
