### ISSUE TITLE
Add an option to save the MJPEG output directly without encoding to H.264

### ISSUE THREAD

**Issue by Calinou** [matanui159/ReplaySorcery#29]
There could be an option to save the MJPEG output directly without encoding the video to H.264. While this will greatly increase file size, it should also be much faster to save the video this way.

Here are some example use cases for this option:

- Encoding the video in another format than H.264 (such as the non-patent-encumbered VP9 or AV1), without suffering from the loss of quality by having to encode the H.264 video in another lossy format.
- Previewing your recording as fast as possible, then encoding it with an efficient preset such as `veryslow` to upload it online.

PS: Thanks for creating this piece of software, it's proven useful to me :slightly_smiling_face:

**Comment by matanui159** [comment]
Thats actually not to bad of an idea. It will still need to be in some container though since raw MJPEG doesn't support audio or frame timing data, and I do wonder about how many video players support MJPEG though.

**Comment by matanui159** [comment]
This is no longer needed since video is currently always encoded to H.264 in memory (instead of MJPEG previously).
