### ISSUE TITLE
Allow formatting of pre/post output commands

### ISSUE THREAD

**Issue by matanui159** [matanui159/ReplaySorcery#30]
Right now if you want the command to prepare the file or do something with the generated file, you have to give the file a consistent name. Would be nice if there was a way to have a special sequence that specifies the new file name.

Originally mentioned: https://github.com/matanui159/ReplaySorcery/issues/22#issuecomment-679112936

**Comment by pseregiet** [comment]
I've got a working patch, might submit it, but I just thought now that it might be more practical to just call the typed command and the filename after a space for example if postOutputCommand is "~/scripts/replay-post-script.sh" just call system("~/scripts/replay-post-script.sh my_video.mp4"); and then in the bash script you can read that as argument one ($1) and do whatever you want with that. If instead you want the string to have some special token that will be replaced with the filename, I made a patch that looks for '%file%' and replaces that with the filename. Can submit if you're interested

**Comment by matanui159** [comment]
Having the argument after probably isn't a good idea since sometimes you don't want to do something with the file.

I was thinking of just passing it through `printf` so it replaced `%s` with the filename but either works.

**Comment by matanui159** [comment]
This had been implemented as part of the FFmpeg rewrite (#37).
