### ISSUE TITLE
Black videos

### ISSUE THREAD

**Issue by bwyan86** [matanui159/ReplaySorcery#4]
Hi there and thanks for making this available.

I've compiled and installed according to the instructions, but get a black video stream in any of the videos that I record.

My specs:
Ubuntu 20.04
Mesa 20.1.4
X11
i3wm
No compositor

I may have found something peculiar in the compile output that may be worth investigating: [https://pastebin.com/zkZneLNt](https://pastebin.com/zkZneLNt)

Otherwise, the log output from running the program seems pretty normal to me: [https://pastebin.com/ifX8yapw](https://pastebin.com/ifX8yapw)

Please let me know if any other input may be helpful and thanks again.

**Comment by PistolRcks** [comment]
Have the same problem as well. Am using:

- Manjaro
- Linux 5.6.17-2-rt9
- Nvidia Driver 440.100
- X11
- Plasma 5.19.3
- Compositor: OpenGL 3.1

Problem persists even when compositor is off.

**Comment by matanui159** [comment]
Sadly the compiler warnings are normal and happen all the time. If either of you has time could they run a debugger through it and see where abouts it goes wrong?

**Comment by matanui159** [comment]
Nvm I started getting this as well but it only happens when running as a service and even then sometimes doesn't happen and works fine. I'll be looking into this.

**Comment by matanui159** [comment]
See if it works now

**Comment by bwyan86** [comment]
@matanui159 Yes, it is working now. Thanks for the quick fix.
