### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Thiago4532** [matanui159/ReplaySorcery#46]
Maybe this is my fault, but ReplaySorcery is using at least 50% of one thread, sometimes get to 80% and pulseuaudio uses 20%.
I am using Arch Linux in the latest stable kernel.

![image](https://user-images.githubusercontent.com/19158283/97214866-7a5d2e80-17a2-11eb-8205-911ffe28affb.png)

**Comment by Calinou** [comment]
What's your screen resolution and configuration options? Also, which window manager are you using? Do you have compositing enabled?

**Comment by matanui159** [comment]
You can try playing with the quality option to see if it reduces the CPU usage. ReplaySorcery is very single threaded however so you can expect it to use a decent chunk of a single thread but I do notice that overall it's only using about 2% (I can't speak much for PulseAudio). I am currently working on a rewrite which I may try to add hardware acceleration which might help in this case.

**Comment by Thiago4532** [comment]
I am using KDE Plasma 5.20 with OpenGL compositor. I'm gonna try to modify some settings to reduce CPU usage.

**Comment by matanui159** [comment]
I had more of a look and I noticed that you're running ReplaySorcery twice? Maybe this is causing some issues, are the logs saying anything of note? Also did you end of finding out if changing the settings helped reduce CPU usage?

**Comment by Thiago4532** [comment]
Replay-sorcery has 3 processes, reducing compress-quality or disable the compositor didn't help at all. Tomorrow I'm gonna try another DE like GNOME or XFCE to see if it's KDE's fault. I have a dedicated NVIDIA GPU in my laptop but I don't use it, maybe I can try to render everything using NVIDIA GPU to see the results.
![image](https://user-images.githubusercontent.com/19158283/98606577-3c91f700-22c6-11eb-9f43-e9c60e802715.png)

**Comment by matanui159** [comment]
I don't know why there are multiple processes? Unless its showing one for each thread. Also can you check if the logs say anything. If you're running using systemd you can use `journalctl --user -fu replay-sorcery`.

**Comment by pseregiet** [comment]
It might indeed be the threads, not sure what htop displays. You can use ps -x | grep replay to see if you have more than one instance of the replay-sorcery running. It should only print out 1 line (actually 2, since it will also show grep running that you just called)

**Comment by matanui159** [comment]
Closing this since the last response was over a month ago
