### ISSUE TITLE
Support for frame sizes not divisible by 8

### ISSUE THREAD

**Issue by benjamimgois** [matanui159/ReplaySorcery#5]
I followed the building and installation process. After i press `Ctrl+Super+R ` i got some [output errors](https://pastebin.com/UFabc0QD) and empty MP4 files are created on the directory.

Manjaro 20.0.3
Gnome 3.36.4
Mesa 20.1.4
X11

**Comment by matanui159** [comment]
As the error suggests, right now it only supports frame sizes divisible by 8. Will work on improving that but for the time being you might just have to lower the frame size to the nearest multiple of 8.

**Comment by benjamimgois** [comment]
Nice ! thanks for the fix

**Comment by cloudrac3r** [comment]
I don't think this is fixed. It outputs "size must be divisible by 2", but the surrounding condition still checks if it's divisible by 8. My screen, which is height 900 pixels, failed the check in practice. I had to change the height to 896 to make it work.

Now that it works, this is an _incredibly_ cool project.

**Comment by matanui159** [comment]
My bad, will put a new commit through now
