### ISSUE TITLE
SDL couldn't find audio devices

### ISSUE THREAD

**Issue by benjamimgois** [matanui159/ReplaySorcery#60]
Hey @matanui159 , firstly thank you very much for this app. I wished for a instant replay app for linux for years, when i saw the first release i instantly though in create a GUI for it in goverlay.

Actually i'm having this problem with my system. It seems SDL doesn't recognise audio devices using the "auto" option.

```
Available devices:
SDL2 couldn't open audio device No such audio device : (null)
Couldn't open any audio device. You will have no sound
```
What should i do ?

**Comment by matanui159** [comment]
What does `pactl list sources` and `pactl list sinks` return?

**Comment by benjamimgois** [comment]
`pactl list sources`

https://pastebin.pl/view/a6c1684f

`pactl list sinks`

https://pastebin.pl/view/ca296bbb

**Comment by matanui159** [comment]
Not sure why that is happening, by the looks of it ReplaySorcery is having trouble getting the default output device from SDL2. @pseregiet might know more since he wrote the audio backend. It also might start working or be more debuggable once the FFmpeg rewrite is done since that uses PulseAudio more directly

**Comment by pseregiet** [comment]
If you build ReplaySorcery yourself (or via aur package if it doesn't just download binary) and you don't have pulse audio headers installed SDL2 will be compiled with no PulseAudio support. Even though SDL2 will load the PulseAudio library using dlopen, therefore not needing PulseAudio libraries when building, it still needs the headers. I was wrong in thinking PulseAudio is not a built requirement. 

Either ReplaySorcery needs to add PulseAudio as dependency or we need to get at least the PA headers into the repo (another git module ?)

**Comment by benjamimgois** [comment]
I just build the latest git version (replay-sorcery-git) and it seems to have fixed the issue. The problem only happens on the stable 0.3.1-1. Anyway thanks for the help ! 

![Captura de tela de 2020-11-24 23-34-07](https://user-images.githubusercontent.com/7688496/100175677-9f31e800-2ead-11eb-8489-318622abf8f5.png)
