### ISSUE TITLE
Error compiling the AUR Package

### ISSUE THREAD

**Issue by benjamimgois** [matanui159/ReplaySorcery#76]
Everytime i tried to compile the AUR package i got the error saiyng that `'../replay-sorcery.default.conf': file or directory can not be found'`

Manjaro 20.2
Gnome 3.38.2

![Captura de tela de 2020-12-19 22-39-59](https://user-images.githubusercontent.com/7688496/102703270-8833ab00-424b-11eb-9a8b-fb0476d9537b.png)

**Comment by matanui159** [comment]
I don't know why that is happening. The file does not exist anymore and isn't referenced in either the CMakeList or the PKG BUILD so I don't know what would be trying to reference it?

Can you try doing a clean install?

**Comment by benjamimgois** [comment]
For some reason simply updating the AUR wasnt working. As you suggested, i removed the old version first and made a clean new installation. It works now. 

Thanks !
