### ISSUE TITLE
The source directory "/some/path/bin" does not exist

### ISSUE THREAD

**Issue by TMiguelT** [matanui159/ReplaySorcery#80]
**Describe the bug**
This bug occurs when trying to compile the source:

1. `git clone git@github.com:matanui159/ReplaySorcery.git --recursive`
2. `cd ReplaySorcery`
3. `cmake -B bin -DCMAKE_BUILD_TYPE=Release`

Then I get the error:
```
CMake Error: The source directory "/media/michael/Storage2/Programming/ReplaySorcery/bin" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Desktop:**
 - Distro: Ubuntu 18.04
 - Desktop Environment: Gnome 3
 - Window Manager: Gnome 3 Wayland
 - Cmake version: 3.10.2

**Comment by matanui159** [comment]
You version of CMake seems to be old and doesn't seem to support the `-B` flag. If you're unable to update you can do this instead:
```
$ mkdir bin
$ cd bin
$ cmake .. -DCMAKE_BUILD_TYPE=Release
$ make
```

**Comment by matanui159** [comment]
Since there are no more comments I am going to assume this issue was fixed and close it for now.

**Comment by TMiguelT** [comment]
Ah actually that workaround works until I hit another issue due to the older cmake version:
```
CMake Error at CMakeLists.txt:63 (target_link_options):
  Unknown CMake command "target_link_options".
Call Stack (most recent call first):
  CMakeLists.txt:67 (target_c_flag)
```

The simpler solution was actually to update the cmake version, which I did using this PPA: https://apt.kitware.com/ (instructions for future users with this issue):
```bash
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
# Change bionic to focal for Ubuntu 20.04
sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
sudo apt-get update
sudo apt-get install cmake
```

Also, because Ubuntu packages ffmpeg libraries separately from the core, I then had to:
```bash
sudo apt install libavutil-dev libavformat-dev libavdevice-dev libavcodec-dev libavfilter-dev 
```

At this point it configured correctly.

**Comment by luni3359** [comment]
> Ah actually that workaround works until I hit another issue due to the older cmake version:
> 
> ```
> CMake Error at CMakeLists.txt:63 (target_link_options):
>   Unknown CMake command "target_link_options".
> Call Stack (most recent call first):
>   CMakeLists.txt:67 (target_c_flag)
> ```
> 
> The simpler solution was actually to update the cmake version, which I did using this PPA: https://apt.kitware.com/ (instructions for future users with this issue):
> 
> ```shell
> wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
> # Change bionic to focal for Ubuntu 20.04
> sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
> sudo apt-get update
> sudo apt-get install cmake
> ```
> 
> Also, because Ubuntu packages ffmpeg libraries separately from the core, I then had to:
> 
> ```shell
> sudo apt install libavutil-dev libavformat-dev libavdevice-dev libavcodec-dev libavfilter-dev 
> ```
> 
> At this point it configured correctly.

I didn't have those packages installed either. I wouldn't have known I had to install the dev ones, thanks dude.

**Comment by matanui159** [comment]
Both of these issues seem to do with an outdated CMake (this is the reason I left Debian-based distros their packages tend to get out of date very quickly).

**Comment by luni3359** [comment]
Just out of curiosity, what version is recommended (or which one do you have)? I have version 3.16.3 installed right now and I only had to install the packages he listed to get it to compile.

**Comment by matanui159** [comment]
I'm not entirely sure. I currently have the minimum required version set to 3.0 but it looks like I have to increase that since both the `-B` flag and the `target_link_options` function was added in 3.13
