### ISSUE TITLE
hwaccel and kms don't work with Nvidia RTX 3090

### ISSUE THREAD

**Issue by gardotd426** [matanui159/ReplaySorcery#84]
**Describe the bug**
With "hwaccel" set as the videoInput option, and literally nothing else changed from the config, replay-sorcery fails to start:

```
FFmpeg version: n4.3.1
[kmsgrab @ 0x559b68472080] Failed to set universal planes capability: primary planes will not be usable.
[kmsgrab @ 0x559b68472080] Failed to get plane resources: Operation not supported.
 - /home/matt/tmp/replaysorcery/src/device/ffdev.c:119 (rsFFmpegDeviceOpen)
 - /home/matt/tmp/replaysorcery/src/device/kmsdev.c:47 (rsKMSDeviceCreate)
 - /home/matt/tmp/replaysorcery/src/device/device.c:50 (rsVideoDeviceCreate)
 - /home/matt/tmp/replaysorcery/src/main.c:162 (main)
Unused option: framerate
Failed to create KMS device: Invalid argument
Function not implemented
 - /home/matt/tmp/replaysorcery/src/main.c:218 (main)
```

`replay-sorcery kms-devices`:

```
Failed to enable DRM universal planes
Failed to get DRM plane resources: Operation not supported
```
Trying to set `kms` as the option instead of hwaccel also does not work. Only x11 works. This is with the latest code, just built 20 minutes ago from a freshly cloned repo.  

**Desktop:**
 - Distro: Arch
 - Desktop Environment: KDE
 - Window Manager: KWin
 - CPU: AMD Ryzen 7 5800X
 - GPU: Nvidia RTX 3090 (driver version 460.27.04-143)

**Configuration:**
Please upload your copy of `/usr/local/etc/replay-sorcery.conf` (`/usr/etc/replay-sorcery.conf` on Arch) and a copy of `~/.config/replay-sorcery.conf` if it exists.

[replay-sorcery.conf.txt](https://github.com/matanui159/ReplaySorcery/files/5737440/replay-sorcery.conf.txt)

**Logs:**
Please run `journalctl --user -eu replay-sorcery -n 100 > replay-sorcery.log` and upload the result.

[replay-sorcery.log](https://github.com/matanui159/ReplaySorcery/files/5737441/replay-sorcery.log)

It's really unfortunate if hw acceleration doesn't work at all, CPU intensive games are just not gonna be ideal to run with no GPU acceleration, even with a 5800X. But the thing is, I know hardware decoding and encoding works with this GPU on this system, I use NVENC encoding and other hw acceleration (h264, vp9, etc.) all the time.

**Comment by matanui159** [comment]
I think the nVidia proprietary drivers don't support VA-API and only support NVENC. I have another issue open to support that (#9).

**Comment by TobiPeterG** [comment]
Hey guys,

I tried to activate hwaccel with my GTX 1080, but `replay-sorcery kms-devices` gives the following messsage:
`libdrm was not found during compilation`

Is this an error that on my side or on the side of replay-sorcery?
Can someone confirm that issue or knows why it appears?

**Comment by matanui159** [comment]
You need the `libdrm` development files during CMake configuration for it to work. If it still doesn't work, it's probably because you're using proprietary drivers and they don't support VA-API. See #9 for details.

**Comment by TobiPeterG** [comment]
> You need the `libdrm` development files during CMake configuration for it to work. If it still doesn't work, it's probably because you're using proprietary drivers and they don't support VA-API. See #9 for details.

Oh OK, thank you, I'm using proprietary drivers

**Comment by gardotd426** [comment]
Yeah you can't use hwaccel or kms with the proprietary drivers.
