### ISSUE TITLE
dual monitors not resizing (resolved but still not starting on boot)

### ISSUE THREAD

**Issue by lorddickfist** [matanui159/ReplaySorcery#85]
Can't get recording to resize to just one monitor. I have a dual monitor setup of both 1920x1080 I looked at issue #83 as it mentioned something similar. You recommended he edit the videowidth I did this and nothing happened (I used sudo nano to edit) I even changed the height too... Still nothing recording both monitors. If you have a suggestion that'd be great!

**Desktop:**
 - Distro: [Arch 5.9.14]
 - Desktop Environment: [None]
 - Window Manager: [Openbox]
 - CPU: [ AMD Ryzen 7 2700x]
 - GPU: [ AMD Radeon RX 6800XT]

**Configuration:**
Please upload your copy of `/usr/local/etc/replay-sorcery.conf` (`/usr/etc/replay-sorcery.conf` on Arch) and a copy of `~/.config/replay-sorcery.conf` if it exists.

[replay-sorcery.txt](https://github.com/matanui159/ReplaySorcery/files/5738710/replay-sorcery.txt)
I had to upload the conf as a .txt instead
**Logs:**
Please run `journalctl --user -eu replay-sorcery -n 100 > replay-sorcery.log` and upload the result.
[replay-sorcery.log](https://github.com/matanui159/ReplaySorcery/files/5738714/replay-sorcery.log)

**Comment by matanui159** [comment]
Have you restarted the service with `systemctl --user restart replay-sorcery`?

**Comment by lorddickfist** [comment]
> Have you restarted the service with `systemctl --user restart replay-sorcery`?

Yes

**Comment by matanui159** [comment]
Theoretically yes, but if that command isn't working there could be something else going wrong.

**Comment by lorddickfist** [comment]
> Theoretically yes, but if that command isn't working there could be something else going wrong.

Yeah just noticed it didn't work on startup either. My other systemd stuff did though. Any recommendations....

**Comment by matanui159** [comment]
Another copy of the replay-sorcery logs might help but I have a feeling your systemd setup is broken, maybe [this](https://bbs.archlinux.org/viewtopic.php?id=234813) might help?

**Comment by lorddickfist** [comment]
> Another copy of the replay-sorcery logs might help but I have a feeling your systemd setup is broken, maybe [this](https://bbs.archlinux.org/viewtopic.php?id=234813) might help?

Will take a look ty

**Comment by lorddickfist** [comment]
> Another copy of the replay-sorcery logs might help but I have a feeling your systemd setup is broken, maybe [this](https://bbs.archlinux.org/viewtopic.php?id=234813) might help?

I fixed my dbus but it sitll refuses to start on startup

**Comment by matanui159** [comment]
Do the logs say anything?

**Comment by lorddickfist** [comment]
For now I have it auto starting via openbox autostart but as far as logs this is what I get from "[journalctl -b --user-unit=replay-sorcery" ](http://ix.io/2K73)

**Comment by matanui159** [comment]
Can you try stopping the service and just running `replay-sorcery` by itself?

**Comment by lorddickfist** [comment]
> Can you try stopping the service and just running `replay-sorcery` by itself?

Yknow I tried "systemctl stop replay-sorcery" and it says its not even loaded which I know its working because I just recorded something. 
My autostart command is even "systemctl --user enable --now replay-sorcery &" So I don't understand how it is not recognized as running?

**Comment by matanui159** [comment]
You need to do `systemctl --user stop replay-sorcery` I'm pretty sure. Also you don't need the `enable --now` in the autostart, enabling it makes systemctl start it on login

**Comment by lorddickfist** [comment]
Running the service itself works fine, [here is the text output of the command while running it](https://ghostbin.co/paste/5fgna)

**Comment by matanui159** [comment]
And it's still recording both monitors?

**Comment by lorddickfist** [comment]
> And it's still recording both monitors?

Oh no its not recording both monitors anymore. I updated the title because of that.

**Comment by matanui159** [comment]
Just run `systemctl --user enable --now replay-sorcery` and it should start now and start on boot. No need to add it to an autostart

**Comment by matanui159** [comment]
Where you able to get this working?
