### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by guglovich** [matanui159/ReplaySorcery#86]
![изображение](https://user-images.githubusercontent.com/54148165/103092045-1078ce00-4607-11eb-9aff-c231e6cdc94d.png)

**Desktop:**
 - Distro: Arch
 - Desktop Environment: Xfce4
 - Window Manager: XFWM
 - CPU: AMD 7850K
 - GPU: AMD RX460

**Configuration:**
Please upload your copy of `/usr/local/etc/replay-sorcery.conf` (`/usr/etc/replay-sorcery.conf` on Arch) and a copy of `~/.config/replay-sorcery.conf` if it exists.
[replay-sorcery.log](https://github.com/matanui159/ReplaySorcery/files/5739740/replay-sorcery.log)

**Logs:**
Please run `journalctl --user -eu replay-sorcery -n 100 > replay-sorcery.log
[replay-sorcery.log](https://github.com/matanui159/ReplaySorcery/files/5739745/replay-sorcery.log)
` and upload the result.

**Comment by matanui159** [comment]
Do you still have a `~/.config/replay-sorcery.conf` file from the old version? Alot of the options have been changed.

**Comment by guglovich** [comment]
> Do you still have a `~/.config/replay-sorcery.conf` file from the old version? Alot of the options have been changed.

I only changed the saving folder of the video, the rest was so originally.

**Comment by matanui159** [comment]
Can you check if there is a `~/.config/replay-sorcery.conf` file? It seems to be reading old config from somewhere else.

**Comment by guglovich** [comment]
> Can you check if there is a `~/.config/replay-sorcery.conf` file? It seems to be reading old config from somewhere else.

Yes, it was, I deleted it. It was created through Goverlay. I thought I didn't have the program working, so I tried Goverlay.
Now I'm wondering if there is a hotkey to stop? Or does the systemd process need to be set to stop? And where is the temporary file cached?

**Comment by matanui159** [comment]
> It was created through Goverlay

Ah, that makes sense. I think Goverlay is in the process of being updated for the latest version.

> Now I'm wondering if there is a hotkey to stop? Or does the systemd process need to be set to stop?

Theres no hotkey to stop, you can stop it with `systemctl --user stop replay-sorcery`.

> And where is the temporary file cached?

There is no temporary file, the saved file at the end is saved to your Videos directory by default. You can change this with the `outputFile` option. You can see [replay-sorcery.conf](https://github.com/matanui159/ReplaySorcery/blob/master/sys/replay-sorcery.conf) for all the new options and documentation.
