### ISSUE TITLE
Failed to create X11 device

### ISSUE THREAD

**Issue by Seltonu** [matanui159/ReplaySorcery#88]
After installing ReplaySorcery and running "journalctl --user -fu replay-sorcery" I get the following output:
Failed to create X11 device. Function not implemented.
Start request repeated too quickly. Failed with result 'exit-code'
![image](https://user-images.githubusercontent.com/10287568/103450923-35f28100-4c72-11eb-9608-ecbe45660b15.png)

**Desktop:**
 - Distro: Pop!_OS 20.10 (Ubuntu flavor)
 - Desktop Environment: Gnome
 - Window Manager: Mutter
 - CPU: AMD Ryzen 3900x
 - GPU: AMD Radeon Vega 64

**Configuration:**

[replay-sorcery.conf.txt](https://github.com/matanui159/ReplaySorcery/files/5759784/replay-sorcery.conf.txt)

**Logs:**

[replay-sorcery.log](https://github.com/matanui159/ReplaySorcery/files/5759786/replay-sorcery.log)

**Comment by matanui159** [comment]
You're missing the X11 development files. Install those and rerun CMake and Make

**Comment by Seltonu** [comment]
I've gone ahead and installed libx11-dev but I get the same issue

**Comment by Seltonu** [comment]
Installing libx11-dev fixed this, thank you! Also needed to install libpulse-dev libdrm-dev libavdevice-dev

Seems to be working now but with no audio captured, can you point me to a solution for this? Pulseaudio is installed
