### ISSUE TITLE
Failed to create PulseaAudio device

### ISSUE THREAD

**Issue by Seltonu** [matanui159/ReplaySorcery#89]
**Describe the bug**
When checking which pulseaudio devices are available to replay-sorcery I get the following output, although pulseaudio is definitely installed:
![image](https://user-images.githubusercontent.com/10287568/103454195-68ae7080-4c96-11eb-9cf1-b1e839262852.png)

**Desktop:**
 - Distro: Pop!_OS 20.20 (Ubuntu flavor)
 - Desktop Environment: Gnome
 - Window Manager: Mutter
 - CPU: AMD Ryzen 3900x
 - GPU: AMD Radeon Vega 64

**Configuration:**
[replay-sorcery.conf.txt](https://github.com/matanui159/ReplaySorcery/files/5759992/replay-sorcery.conf.txt)

**Logs:**
[replay-sorcery.log](https://github.com/matanui159/ReplaySorcery/files/5759993/replay-sorcery.log)

**Comment by matanui159** [comment]
What exactly is the issue here? `strings` gets all the strings in the executable so of course it's showing all the error messages

**Comment by Seltonu** [comment]
Apologies I wasn't clear, my recordings have no audio yet pulseaudio is installed

**Comment by matanui159** [comment]
Ah ok. Looking through the logs it looks like you're missing the PulseAudio development files. Install those and rerun CMake and Make.

**Comment by Seltonu** [comment]
Ah it seems this was fixed with a restart+recompile, as I had libpulse-dev installed. Thank you!
