### ISSUE TITLE
ReplaySorcery Spams in the syslog after Pulseaudio restarted

### ISSUE THREAD

**Issue by Gladox114** [matanui159/ReplaySorcery#92]
**Describe the bug**
I restarted pulseaudio a few times and got a message 2 hours later or so saying that my root system is full. The syslog was 120GB large and with `sudo tail -n20 /var/log/syslog` I can only see ReplaySorcery saying something about pulseaudio multiple times repeating within the same second.

**Desktop:**
 - Distro: Pop!_OS 20.10
 - Desktop Environment: Gnome

**Logs:**

Syslog

> Jan  7 00:40:47 pop-os replay-sorcery[4279]: Failed to setup PulseAudio stream
> Jan  7 00:40:47 pop-os replay-sorcery[4279]:  - /home/user/Workplace/github/ReplaySorcery/src/audio/pulsedev.c:176 (pulseDeviceRead)
> Jan  7 00:40:47 pop-os replay-sorcery[4279]:  - /home/user/Workplace/github/ReplaySorcery/src/audio/pulsedev.c:218 (pulseDeviceNextFrame)
> Jan  7 00:40:47 pop-os replay-sorcery[4279]:  - /home/user/Workplace/github/ReplaySorcery/src/audio/../device/device.h:34 (rsDeviceNextFrame)
> Jan  7 00:40:47 pop-os replay-sorcery[4279]:  - /home/user/Workplace/github/ReplaySorcery/src/audio/audio.c:30 (audioThread)
> Jan  7 00:40:47 pop-os replay-sorcery[4279]: Failed to frame from audio device: Generic error in an external library

**Comment by matanui159** [comment]
Looks like I might have to do something similar to what I do for video where if reading a frame is failing it silences logs until it works again. Only concern is all logs will be silenced including video (due to FFmpeg only having one log context).
